### ISSUE TITLE
Add light/dark mode toggler

### ISSUE THREAD

**Issue by johncmanuel** [johncmanuel/RateMyLoo#3]
Add a button that toggles light/dark mode for the user.

**Comment by KyleLee8** [comment]
Here is some idea how to make it https://www.w3schools.com/howto/howto_js_toggle_dark_mode.asp

**Comment by johncmanuel** [comment]
That's a good start. We can use React to define a component that is applied to all pages. Inside the component, we can use TailwindCSS's dark variant feature for styling. We'll need to use React's states to trigger the switch between light and dark mode, then store the setting in one of the browser storages called localStorage. That way, the browser will remember the user's preference.

Reference:
- [TailwindCSS Dark Mode](https://tailwindcss.com/docs/dark-mode)
- [React docs on states](https://react.dev/learn/state-a-components-memory)
- [Guide on localStorage](https://www.w3schools.com/jsref/prop_win_localstorage.asp)

**Comment by KyleLee8** [comment]
the issues i am having right now is i can see the toggle button to change the light and dark mode but It's not functioning correctly i think this might  be related about global.css i will keep looking for it

**Comment by KyleLee8** [comment]
i think i am going on the right track? i guess now i can see at least the toggler is changing light and dark mode

**Comment by johncmanuel** [comment]
Could you create a branch containing your current code and send it here?

EDIT: Also send screenshots of your progress.

**Comment by KyleLee8** [comment]
yes i will do that tmw sir

**Comment by KyleLee8** [comment]
![이미지 11-30-23 오후 2 45](https://github.com/johncmanuel/RateMyLoo/assets/69995956/9321e57d-90c7-4911-9d67-82d9c72176f5)

**Comment by KyleLee8** [comment]
![image](https://github.com/johncmanuel/RateMyLoo/assets/69995956/9b58f7b5-c7ca-44c2-b536-6dd217102cb9)

**Comment by johncmanuel** [comment]
Link to @ipark604's branch for user page design: <https://github.com/johncmanuel/RateMyLoo/tree/user>

Things to cover for review later:

1. Fix placement of newly added/modified files (they are located in the root at first glance)
2. Go over the code made by @ipark604 
3. When finished, create a pull request and check if things are working as intended in the Preview deployment
4. Merge with main branch after another review
